version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: oneccess_frontend:latest
    container_name: oneccess_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
